config/routes.rb
Rails.application.routes.draw do
  
  resources :cars
  resources :bodies
  resources :wheels
  resources :spoilers
  resources :paints
  resources :users

  get '/login', to: 'users#token_authenticate'
  post '/login', to: 'auth#create'
  post '/signup', to: 'users#signup'
  get '/profile', to: 'users#profile'

end

app/models/body.rb
class Body < ApplicationRecord
   has_many :car
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

   def index 
      bodies = Body.all
      render json: bodies
   end 

   def create
      body = Body.create!({ 
         partType: permitted_params['partType'],
         name: permitted_params['name'],
         image: permitted_params['image'],
         speed: permitted_params['speed'],
         efficency: permitted_params['efficency'],
         power: permitted_params['power']
      })
      render json: body
   end

   def show
      body = Body.find_by(id: params[:id])
      render json: body
   end 

   def permitted_params
      params.require(:body).permit(:partType, :name, :image, :speed, :efficency, :power)
   end

end

app/views/bodies/_form.html.erb
<%= form_with(model: body) do |form| %>
  <% if body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(body.errors.count, "error") %> prohibited this body from being saved:</h2>

      <ul>
        <% body.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :efficency %>
    <%= form.number_field :efficency %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bodies/edit.html.erb
<h1>Editing Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Show', @body %> |
<%= link_to 'Back', bodies_path %>

app/views/bodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bodies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Efficency</th>
      <th>Power</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodies.each do |body| %>
      <tr>
        <td><%= body.name %></td>
        <td><%= body.speed %></td>
        <td><%= body.efficency %></td>
        <td><%= body.power %></td>
        <td><%= link_to 'Show', body %></td>
        <td><%= link_to 'Edit', edit_body_path(body) %></td>
        <td><%= link_to 'Destroy', body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Body', new_body_path %>

app/views/bodies/new.html.erb
<h1>New Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Back', bodies_path %>

app/views/bodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @body.name %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @body.speed %>
</p>

<p>
  <strong>Efficency:</strong>
  <%= @body.efficency %>
</p>

<p>
  <strong>Power:</strong>
  <%= @body.power %>
</p>

<%= link_to 'Edit', edit_body_path(@body) %> |
<%= link_to 'Back', bodies_path %>