config/routes.rb
Rails.application.routes.draw do
  
  resources :cars
  resources :bodies
  resources :wheels
  resources :spoilers
  resources :paints
  resources :users

  get '/login', to: 'users#token_authenticate'
  post '/login', to: 'auth#create'
  post '/signup', to: 'users#signup'
  get '/profile', to: 'users#profile'

end

app/models/paint.rb
class Paint < ApplicationRecord
   has_many :car
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController

   def index 
      paints = Paint.all
      render json: paints
   end 
   
   def create
      paint = Paint.create!({ 
         partType: permitted_params['partType'],
         name: permitted_params['name'],
         image: permitted_params['image']
      })
      render json: paint
   end

   def show
      paint = Paint.find_by(id: params[:id])
      render json: paint
   end

   def permitted_params
      params.require(:paint).permit(:partType, :name, :image)
   end

end

app/views/paints/_form.html.erb
<%= form_with(model: paint) do |form| %>
  <% if paint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paint.errors.count, "error") %> prohibited this paint from being saved:</h2>

      <ul>
        <% paint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paints/edit.html.erb
<h1>Editing Paint</h1>

<%= render 'form', paint: @paint %>

<%= link_to 'Show', @paint %> |
<%= link_to 'Back', paints_path %>

app/views/paints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paints</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paints.each do |paint| %>
      <tr>
        <td><%= paint.name %></td>
        <td><%= link_to 'Show', paint %></td>
        <td><%= link_to 'Edit', edit_paint_path(paint) %></td>
        <td><%= link_to 'Destroy', paint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paint', new_paint_path %>

app/views/paints/new.html.erb
<h1>New Paint</h1>

<%= render 'form', paint: @paint %>

<%= link_to 'Back', paints_path %>

app/views/paints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @paint.name %>
</p>

<%= link_to 'Edit', edit_paint_path(@paint) %> |
<%= link_to 'Back', paints_path %>