config/routes.rb
Rails.application.routes.draw do
  
  resources :cars
  resources :bodies
  resources :wheels
  resources :spoilers
  resources :paints
  resources :users

  get '/login', to: 'users#token_authenticate'
  post '/login', to: 'auth#create'
  post '/signup', to: 'users#signup'
  get '/profile', to: 'users#profile'

end

app/models/wheel.rb
class Wheel < ApplicationRecord
   has_many :car
end

app/controllers/wheels_controller.rb
class WheelsController < ApplicationController

   def index 
      wheels = Wheel.all
      render json: wheels
   end 

   def create
      wheel = Wheel.create!({ 
         partType: permitted_params['partType'],
         name: permitted_params['name'],
         image: permitted_params['image'],
         speed: permitted_params['speed'],
         efficency: permitted_params['efficency'],
         power: permitted_params['power']
      })
      render json: wheel
   end

   def show
      wheel = Wheel.find_by(id: params[:id])
      render json: wheel
   end 

   def permitted_params
      params.require(:wheel).permit(:partType, :name, :image, :speed, :efficency, :power)
   end

end

app/views/wheels/_form.html.erb
<%= form_with(model: wheel) do |form| %>
  <% if wheel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wheel.errors.count, "error") %> prohibited this wheel from being saved:</h2>

      <ul>
        <% wheel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :efficency %>
    <%= form.number_field :efficency %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wheels/edit.html.erb
<h1>Editing Wheel</h1>

<%= render 'form', wheel: @wheel %>

<%= link_to 'Show', @wheel %> |
<%= link_to 'Back', wheels_path %>

app/views/wheels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wheels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Efficency</th>
      <th>Power</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wheels.each do |wheel| %>
      <tr>
        <td><%= wheel.name %></td>
        <td><%= wheel.speed %></td>
        <td><%= wheel.efficency %></td>
        <td><%= wheel.power %></td>
        <td><%= link_to 'Show', wheel %></td>
        <td><%= link_to 'Edit', edit_wheel_path(wheel) %></td>
        <td><%= link_to 'Destroy', wheel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wheel', new_wheel_path %>

app/views/wheels/new.html.erb
<h1>New Wheel</h1>

<%= render 'form', wheel: @wheel %>

<%= link_to 'Back', wheels_path %>

app/views/wheels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wheel.name %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @wheel.speed %>
</p>

<p>
  <strong>Efficency:</strong>
  <%= @wheel.efficency %>
</p>

<p>
  <strong>Power:</strong>
  <%= @wheel.power %>
</p>

<%= link_to 'Edit', edit_wheel_path(@wheel) %> |
<%= link_to 'Back', wheels_path %>