config/routes.rb
Rails.application.routes.draw do
  
  resources :cars
  resources :bodies
  resources :wheels
  resources :spoilers
  resources :paints
  resources :users

  get '/login', to: 'users#token_authenticate'
  post '/login', to: 'auth#create'
  post '/signup', to: 'users#signup'
  get '/profile', to: 'users#profile'

end

app/models/spoiler.rb
class Spoiler < ApplicationRecord
   has_many :car
end

app/controllers/spoilers_controller.rb
class SpoilersController < ApplicationController

   def index 
      spoilers = Spoiler.all
      render json: spoilers
   end 

   def create
      spoiler = Spoiler.create!({ 
         partType: permitted_params['partType'],
         name: permitted_params['name'],
         image: permitted_params['image'],
         speed: permitted_params['speed'],
         efficency: permitted_params['efficency'],
         power: permitted_params['power']
      })
      render json: spoiler
   end

   def show
      spoiler = Spoiler.find_by(id: params[:id])
      render json: spoiler
   end 

   def permitted_params
      params.require(:spoiler).permit(:partType, :name, :image, :speed, :efficency, :power)
   end
   
end

app/views/spoilers/_form.html.erb
<%= form_with(model: spoiler) do |form| %>
  <% if spoiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spoiler.errors.count, "error") %> prohibited this spoiler from being saved:</h2>

      <ul>
        <% spoiler.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>

  <div class="field">
    <%= form.label :efficency %>
    <%= form.number_field :efficency %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spoilers/edit.html.erb
<h1>Editing Spoiler</h1>

<%= render 'form', spoiler: @spoiler %>

<%= link_to 'Show', @spoiler %> |
<%= link_to 'Back', spoilers_path %>

app/views/spoilers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spoilers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speed</th>
      <th>Efficency</th>
      <th>Power</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spoilers.each do |spoiler| %>
      <tr>
        <td><%= spoiler.name %></td>
        <td><%= spoiler.speed %></td>
        <td><%= spoiler.efficency %></td>
        <td><%= spoiler.power %></td>
        <td><%= link_to 'Show', spoiler %></td>
        <td><%= link_to 'Edit', edit_spoiler_path(spoiler) %></td>
        <td><%= link_to 'Destroy', spoiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spoiler', new_spoiler_path %>

app/views/spoilers/new.html.erb
<h1>New Spoiler</h1>

<%= render 'form', spoiler: @spoiler %>

<%= link_to 'Back', spoilers_path %>

app/views/spoilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spoiler.name %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @spoiler.speed %>
</p>

<p>
  <strong>Efficency:</strong>
  <%= @spoiler.efficency %>
</p>

<p>
  <strong>Power:</strong>
  <%= @spoiler.power %>
</p>

<%= link_to 'Edit', edit_spoiler_path(@spoiler) %> |
<%= link_to 'Back', spoilers_path %>